/**
 * Patches window.fetch to proxy external API calls through our server,
 * avoiding CORS issues with APIs that the Atomiq SDK uses internally:
 *   - mempool.space / mempool.holdings (Bitcoin blockchain data)
 *   - okx.com, binance.com, coingecko.com, coinpaprika.com, kraken.com (price feeds)
 *   - nodes.atomiq.exchange (Atomiq intermediary nodes for swap creation)
 *
 * The SDK generates malformed mempool URLs (missing slashes between path
 * segments like "apiaddress" instead of "api/address"). This patch fixes
 * those before proxying.
 */

import { API_URL } from "@/lib/constants";

let patched = false;

/**
 * Fix malformed mempool.space URLs generated by the Atomiq SDK.
 * Examples:
 *   /testnet4/apiaddress/<addr>/utxo  → /testnet4/api/address/<addr>/utxo
 *   /testnet4/apiv1/fees/recommended  → /testnet4/api/v1/fees/recommended
 *   /testnet4/apiv1/cpfp/<txid>       → /testnet4/api/v1/cpfp/<txid>
 *   /testnet4/apitx                   → /testnet4/api/tx
 */
function fixMempoolPath(path: string): string {
  // "apiaddress" → "api/address"
  path = path.replace(/\/api(address|tx|block|blocks|mining|fees|v1|lightning)/g, "/api/$1");
  return path;
}

export function patchFetchForAtomiq(): void {
  if (typeof window === "undefined" || patched) return;
  patched = true;

  const originalFetch = window.fetch.bind(window);

  window.fetch = function (
    input: RequestInfo | URL,
    init?: RequestInit
  ): Promise<Response> {
    let url: string;
    if (typeof input === "string") {
      url = input;
    } else if (input instanceof URL) {
      url = input.href;
    } else if (input instanceof Request) {
      url = input.url;
      // Preserve method/headers from Request object if no init provided
      if (!init) {
        init = {
          method: input.method,
          headers: input.headers,
          body: input.body,
        };
      }
    } else {
      url = String(input);
    }

    // Proxy mempool.space and mempool.holdings requests
    if (url.includes("mempool.space") || url.includes("mempool.holdings")) {
      let proxied = url.replace(/https?:\/\/mempool\.(space|holdings)/, "/proxy/mempool");
      proxied = fixMempoolPath(proxied);
      return originalFetch(proxied, init);
    }

    // Proxy okx.com requests
    if (url.includes("okx.com")) {
      const proxied = url.replace(/https?:\/\/(www\.)?okx\.com/, "/proxy/okx");
      return originalFetch(proxied, init);
    }

    // Proxy price provider APIs (Binance, CoinGecko, CoinPaprika, Kraken)
    if (url.includes("api.binance.com")) {
      const proxied = url.replace(/https?:\/\/api\.binance\.com/, "/proxy/binance");
      return originalFetch(proxied, init);
    }
    if (url.includes("api.coingecko.com")) {
      const proxied = url.replace(/https?:\/\/api\.coingecko\.com/, "/proxy/coingecko");
      return originalFetch(proxied, init);
    }
    if (url.includes("api.coinpaprika.com")) {
      const proxied = url.replace(/https?:\/\/api\.coinpaprika\.com/, "/proxy/coinpaprika");
      return originalFetch(proxied, init);
    }
    if (url.includes("api.kraken.com")) {
      const proxied = url.replace(/https?:\/\/api\.kraken\.com/, "/proxy/kraken");
      return originalFetch(proxied, init);
    }

    // Proxy Atomiq intermediary nodes (return HTML error pages when hit directly)
    if (url.includes("nodes.atomiq.exchange")) {
      const proxied = `${API_URL}/proxy/atomiq-nodes?url=${encodeURIComponent(url)}`;
      return originalFetch(proxied, init);
    }

    return originalFetch(input, init);
  };
}
